language: c++
compiler: gcc
sudo: required
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -y libboost-python-dev libpython-dev
 - build-scripts/install-of.sh
 - build-scripts/generate-project.sh
script: make Release